### ISSUE TITLE
Potential Create Incompatibility

### ISSUE THREAD

**Issue by PolyframeX** [MeatWheeze/NeepMeat#10]
The mod seems to crash when using create schematics occasionally. Giving this error log:

```
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[minecraft-1.20.1.i0:0/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[minecraft-1.20.1.i0:0/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:288) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.24.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.24.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.24.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.24.0.jar:?]
Caused by: java.lang.IllegalStateException: FluidNodeManager can only exist on the logical server
	at com.neep.neepmeat.transport.fluid_network.FluidNodeManager.getInstance(FluidNodeManager.java:50) ~[neepmeat-0.2.22-beta1.20.1.i0:0/:?]
	at com.neep.neepmeat.transport.machine.fluid.FluidPipeBlockEntity.method_11007(FluidPipeBlockEntity.java:219) ~[neepmeat-0.2.22-beta1.20.1.i0:0/:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:84) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_2586.method_38243(class_2586.java:74) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_3499.method_15174(class_3499.java:112) ~[minecraft-1.20.1.i0:0/:?]
	at com.simibubi.create.content.schematics.SchematicExport.saveSchematic(SchematicExport.java:46) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at com.simibubi.create.content.schematics.client.SchematicAndQuillHandler.saveSchematic(SchematicAndQuillHandler.java:205) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at com.simibubi.create.content.schematics.client.SchematicPromptScreen.confirm(SchematicPromptScreen.java:109) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at com.simibubi.create.content.schematics.client.SchematicPromptScreen.lambda$init$1(SchematicPromptScreen.java:64) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at com.simibubi.create.foundation.gui.widget.AbstractSimiWidget.lambda$withCallback$1(AbstractSimiWidget.java:56) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at com.simibubi.create.foundation.gui.widget.AbstractSimiWidget.runCallback(AbstractSimiWidget.java:92) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at com.simibubi.create.foundation.gui.widget.AbstractSimiWidget.method_25348(AbstractSimiWidget.java:97) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[minecraft-1.20.1.i0:0/:?]
	at com.simibubi.create.foundation.gui.AbstractSimiScreen.method_25402(AbstractSimiScreen.java:76) ~[create-0.5.1-f-build.1417mc1.20.1.i0:0/:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[minecraft-1.20.1.i0:0/:?]
	... 20 more
```
I am on the latest version of neepmeat 1.20.1. On the quilt modloader.

**Comment by MeatWheeze** [comment]
Looks like Create is writing block entities to NBT on the logical client, which is not something I would ever expect to happen. I should be able to make this happen safely.
