### ISSUE TITLE
NeepMeat breake KubeJS mod 

### ISSUE THREAD

**Issue by Kisuny** [MeatWheeze/NeepMeat#5]
I liked your mod, but it breaks some kubejs crafts, to be precise, everything.

I understand that your mod is not present in the log, but the problem with crafting appears as soon as I add your mod!

Version mod: NeepMeat: 0.2.6-alpha+1.19.2

Let me know if you need more information!

Error from KubeJS:
<details>
  <summary>Log text</summary>
  
[18:15:49] [KubeJS Recipe Event Worker 0/ERROR]: Could not parse ad_astra:conversion/oxygen_from_water
[18:15:49] [Server thread/ERROR]: Error occurred while handling event 'ServerEvents.recipes': java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: Vanilla crafting methods are not supported
[18:15:49] [Server thread/ERROR]: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: Vanilla crafting methods are not supported
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.joinForPoolInvoke(ForkJoinTask.java:1042)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2639)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS.runInParallel(RecipesEventJS.java:677)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS.forEachRecipeAsync(RecipesEventJS.java:507)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS.remove(RecipesEventJS.java:542)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.NativeArray.iterativeMethod(NativeArray.java:1314)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.NativeArray.execIdCall(NativeArray.java:1798)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.IdFunctionObject.call(IdFunctionObject.java:103)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.doTopCall(Context.java:1325)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[18:15:49] [Server thread/ERROR]: 	at jdk.proxy2/jdk.proxy2.$Proxy109.onEvent(Unknown Source)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:271)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:188)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS.post(RecipesEventJS.java:307)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1863.handler$hin000$kubejs$customRecipesHead(class_1863.java:7531)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1863.method_20705(class_1863.java)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1863.method_18788(class_1863.java:35)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4080.method_18790(class_4080.java:13)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014.method_18365(class_4014.java:69)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014.method_18367(class_4014.java:68)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014.method_18365(class_4014.java:69)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014.method_18367(class_4014.java:68)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014.method_18365(class_4014.java:69)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1255.execute(class_1255.java:103)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014.method_18367(class_4014.java:68)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_4014$1.method_18374(class_4014.java:51)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1255.redirect$bmf000$c2me-opts-scheduling$redirectExecuteTask(class_1255.java:1021)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:19777)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:140)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1316)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_3097.method_29480(class_3097.java:22)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_3097.method_13530(class_3097.java:53)
[18:15:49] [Server thread/ERROR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_2170.redirect$zhd000$architectury$performCommand(class_2170.java:1045)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:271)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_2170.method_44252(class_2170.java:264)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.core.MinecraftServerKJS.kjs$runCommandSilent(MinecraftServerKJS.java:71)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.MemberBox.invoke(MemberBox.java:160)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Interpreter.interpretLoop(Interpreter.java:987)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Interpreter.interpret(Interpreter.java:370)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.doTopCall(Context.java:1325)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.ArrowFunction.call(ArrowFunction.java:42)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.Context.callSync(Context.java:1308)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[18:15:49] [Server thread/ERROR]: 	at jdk.proxy2/jdk.proxy2.$Proxy109.onEvent(Unknown Source)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.postToHandlers(EventHandler.java:301)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:271)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:225)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.event.EventHandler.post(EventHandler.java:188)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.server.KubeJSServerEventHandler.serverStarting(KubeJSServerEventHandler.java:75)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1132.handler$zjd001$architectury$initServer(class_1132.java:535)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.class_1132.method_3823(class_1132.java:74)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
[18:15:49] [Server thread/ERROR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:15:49] [Server thread/ERROR]: Caused by: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: Vanilla crafting methods are not supported
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[18:15:49] [Server thread/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS.lambda$forEachRecipeAsync$11(RecipesEventJS.java:507)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[18:15:49] [Server thread/ERROR]: Caused by: java.lang.UnsupportedOperationException: Vanilla crafting methods are not supported
[18:15:49] [Server thread/ERROR]: 	at com.neep.meatlib.recipe.ImplementedRecipe.method_8110(ImplementedRecipe.java:29)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.JsonRecipeJS.hasOutput(JsonRecipeJS.java:37)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.filter.OutputFilter.test(OutputFilter.java:15)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:456)
[18:15:49] [Server thread/ERROR]: 	at dev.latvian.mods.kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:453)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
[18:15:49] [Server thread/ERROR]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[18:15:49] [Server thread/ERROR]: 	... 5 more
  
</details>

**Comment by MeatWheeze** [comment]
I'm unable to replicate with just KubeJS and NeepMeat. Could you provide the full mod list? 
I am not familiar with KubeJS, but this looks like it's something to do with recipe editing. What specific features are used in your scripts?
Do these errors occur constantly while the server is running or just after joining/datapack reload?

**Comment by Kisuny** [comment]
For more simple example i will delete all mods and most scripts. 

mod list and scirpt example for replicate error:

<details>
  <summary>Mod list</summary>
  
- neepmeat-0.2.6-alpha+1.19.2
- architectury-6.5.85-fabric
- emi-1.0.27+1.19.2+fabric
- fabric-api-0.77.0+1.19.2
- geckolib-fabric-1.19-3.1.40
- kubejs-fabric-1902.6.2-build.39
- rhino-fabric-1902.2.2-build.280

  </details>
  
Put minecraft.js into kubejs\server_scripts in minecraft folder with this script:
<details>

<summary>Script example</summary>

```js
//priority: 0

ServerEvents.recipes(event => {
    const removeByOutput = [
        'minecraft:furnace',
        'minecraft:diamond_sword',
    ]
    removeByOutput.forEach(element => event.remove({ output: element }))

    event.remove({ output: 'minecraft:oak_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:spruce_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:birch_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:jungle_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:acacia_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:dark_oak_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:crimson_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:warped_planks', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:mangrove_planks', type: 'minecraft:crafting_shapeless' })


    // Crafting Table
    event.shapeless('2x minecraft:oak_planks', [
        '#minecraft:oak_logs'
    ]),
        event.shapeless('2x minecraft:spruce_planks', [
            '#minecraft:spruce_logs'
        ]),
        event.shapeless('2x minecraft:birch_planks', [
            '#minecraft:birch_logs'
        ]),
        event.shapeless('2x minecraft:jungle_planks', [
            '#minecraft:jungle_logs'
        ]),
        event.shapeless('2x minecraft:acacia_planks', [
            '#minecraft:acacia_logs'
        ]),
        event.shapeless('2x minecraft:dark_oak_planks', [
            '#minecraft:dark_oak_logs'
        ]),
        event.shapeless('2x minecraft:crimson_planks', [
            '#minecraft:crimson_stems'
        ]),
        event.shapeless('2x minecraft:warped_planks', [
            '#minecraft:warped_stems'
        ]),
        event.shapeless('2x minecraft:mangrove_planks', [
            'minecraft:mangrove_log'
        ])


    event.remove({ id: 'minecraft:stick' })
    event.shaped('2x minecraft:stick', [
        'S  ',
        'S  ',
        '   '
    ], {
        S: '#minecraft:planks'
    })

    event.remove({ id: 'minecraft:crafting_table' })
    event.shaped('minecraft:crafting_table', [
        'FF ',
        'LL ',
        '   '
    ], {
        L: '#minecraft:logs_that_burn',
        F: 'minecraft:flint'
    })

    event.shaped('minecraft:furnace', [
        'CCC',
        'CFC',
        'CCC'
    ], {
        C: '#c:cobblestone',
        F: 'minecraft:campfire'
    })
})

```

</details>


I think the problem is in the forEach loop

**Comment by MeatWheeze** [comment]
Thanks for your help. I've found the issue in [ImplementedInventory](https://github.com/MeatWheeze/NeepMeat/blob/edea9bf0f9b638d9d75aa5da3e6cb0bc552ca389/src/main/java/com/neep/meatlib/recipe/ImplementedRecipe.java) and a couple of others.
I'll release a fixed version shortly.
